/// Herpetofauna species catalog — source: "Vrste za aplikaciju.xlsx" (rows 1-50).
/// Latin name is also the translation key: `'species.<latin>'.tr()` gives the
/// common name in the active language.
const kSpecies = [
  // Amphibia — Caudata
  'Salamandra salamandra',
  'Salamandra atra',
  'Ichthyosaura alpestris',
  'Lissotriton vulgaris',
  'Triturus cristatus',
  'Triturus dobrogicus',
  'Triturus ivanbureschi',
  'Triturus macedonicus',
  // Amphibia — Anura
  'Bombina bombina',
  'Bombina variegata',
  'Pelobates balcanicus',
  'Pelobates fuscus',
  'Bufo bufo',
  'Bufotes viridis',
  'Hyla arborea',
  'Hyla orientalis',
  'Pelophylax kl. esculentus',
  'Pelophylax lessonae',
  'Pelophylax ridibundus',
  'Rana dalmatina',
  'Rana graeca',
  'Rana temporaria',
  // Reptilia — Testudines
  'Testudo graeca',
  'Testudo hermanni',
  'Trachemys scripta',
  'Emys orbicularis',
  // Reptilia — Sauria
  'Mediodactylus kotschyi',
  'Hemidactylus turcicus',
  'Algyroides nigropunctatus',
  'Darevskia praticola',
  'Lacerta agilis',
  'Lacerta trilineata',
  'Lacerta viridis',
  'Podarcis erhardii',
  'Podarcis muralis',
  'Podarcis tauricus',
  'Zootoca vivipara',
  'Ablepharus kitaibelii',
  'Anguis colchica',
  'Anguis fragilis',
  // Reptilia — Serpentes
  'Natrix natrix',
  'Natrix tessellata',
  'Coronella austriaca',
  'Dolichophis caspius',
  'Elaphe quatuorlineata',
  'Platyceps najadum',
  'Zamenis longissimus',
  'Vipera ammodytes',
  'Vipera berus',
  'Vipera ursinii',
];
